---
- import_tasks: "prepare_host.yml"
  when: prepare_host | default(true)

- name: "Create dir"
  file:
    path: "~/{{ app_dir }}"
    state: "directory"

- name: "Copy files"
  copy:
    src: "{{ item }}"
    dest: "~/{{ app_dir }}/{{ item }}"
  with_items:
    - "sockd.conf"

- name: "Copy templates"
  template:
    src: "{{ item }}.j2"
    dest: "{{ app_dir }}/{{ item }}"
  no_log: true
  with_items:
    - "Dockerfile"
    - "docker-compose.yml"

- name: "Run container"
  shell: "docker-compose up -d"
  args:
    chdir: "~/{{ app_dir }}"