---
- name: "Apt update"
  apt:
    update_cache: yes

- name: "Apt upgrade"
  apt:
    name: "*"
    state: "latest"

- name: "Install soft"
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - "docker"
    - "docker-compose"

- name: "Remove useless packages from the cache"
  apt:
    autoclean: yes

- name: "Remove dependencies that are no longer required"
  apt:
    autoremove: yes
