---
- name: "Clear soft"
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - "docker-compose"
    - "docker"

- name: "Remove useless packages from the cache"
  apt:
    autoclean: yes

- name: "Remove dependencies that are no longer required"
  apt:
    autoremove: yes
